<a href="https://colab.research.google.com/github/paras3c/cyber-threat-detection/blob/main/malwaredetectionmodel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importing the libraries

In [4]:
import numpy as np
import pandas as pd

import sklearn
import time

In [5]:
st = time.time()

### Importing the dataset

In [6]:
df = pd.read_csv("/content/TUANDROMD.csv", on_bad_lines='skip')

In [7]:
df.head()

ACCESS_ALL_DOWNLOADS  ACCESS_CACHE_FILESYSTEM  ACCESS_CHECKIN_PROPERTIES  \
0                   0.0                      0.0                        0.0   
1                   0.0                      0.0                        0.0   
2                   0.0                      0.0                        0.0   
3                   0.0                      0.0                        0.0   
4                   0.0                      0.0                        0.0   

   ACCESS_COARSE_LOCATION  ACCESS_COARSE_UPDATES  ACCESS_FINE_LOCATION  \
0                     0.0                    0.0                   0.0   
1                     0.0                    0.0                   0.0   
2                     0.0                    0.0                   0.0   
3                     0.0                    0.0                   0.0   
4                     0.0                    0.0                   0.0   

   ACCESS_LOCATION_EXTRA_COMMANDS  ACCESS_MOCK_LOCATION  ACCESS_MTK_MMHW  \
0                             0.0                   0.0              0.0   
1                             0.0                   0.0              0.0   
2                             0.0                   0.0              0.0   
3                             0.0                   0.0              0.0   
4                             0.0                   0.0              0.0   

   ACCESS_NETWORK_STATE  ...  \
0                   1.0  ...   
1                   1.0  ...   
2                   1.0  ...   
3                   0.0  ...   
4                   0.0  ...   

   Landroid/telephony/TelephonyManager;->getLine1Number  \
0                                                1.0      
1                                                0.0      
2                                                0.0      
3                                                0.0      
4                                                0.0      

   Landroid/telephony/TelephonyManager;->getNetworkOperator  \
0                                                1.0          
1                                                0.0          
2                                                0.0          
3                                                1.0          
4                                                0.0          

   Landroid/telephony/TelephonyManager;->getNetworkOperatorName  \
0                                                1.0              
1                                                0.0              
2                                                0.0              
3                                                1.0              
4                                                0.0              

   Landroid/telephony/TelephonyManager;->getNetworkCountryIso  \
0                                                0.0            
1                                                1.0            
2                                                0.0            
3                                                1.0            
4                                                0.0            

   Landroid/telephony/TelephonyManager;->getSimOperator  \
0                                                0.0      
1                                                0.0      
2                                                0.0      
3                                                1.0      
4                                                0.0      

   Landroid/telephony/TelephonyManager;->getSimOperatorName  \
0                                                0.0          
1                                                0.0          
2                                                0.0          
3                                                0.0          
4                                                0.0          

   Landroid/telephony/TelephonyManager;->getSimCountryIso  \
0                                                0.0        
1                                                

In [8]:
df.shape

(4465, 242)

In [9]:
df['Label']

0        malware
1        malware
2        malware
3        malware
4        malware
          ...   
4460    goodware
4461    goodware
4462    goodware
4463    goodware
4464    goodware
Name: Label, Length: 4465, dtype: object

### Converting all columns to numeric datatypes

In [10]:
df.dtypes

ACCESS_ALL_DOWNLOADS                                        float64
ACCESS_CACHE_FILESYSTEM                                     float64
ACCESS_CHECKIN_PROPERTIES                                   float64
ACCESS_COARSE_LOCATION                                      float64
ACCESS_COARSE_UPDATES                                       float64
                                                             ...   
Landroid/telephony/TelephonyManager;->getSimOperatorName    float64
Landroid/telephony/TelephonyManager;->getSimCountryIso      float64
Landroid/telephony/TelephonyManager;->getSimSerialNumber    float64
Lorg/apache/http/impl/client/DefaultHttpClient;->execute    float64
Label                                                        object
Length: 242, dtype: object

In [11]:
# Convert all columns except 'Label' to numeric
for col in df.columns:
    if col != 'Label':
        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

In [12]:
df.head()

ACCESS_ALL_DOWNLOADS  ACCESS_CACHE_FILESYSTEM  ACCESS_CHECKIN_PROPERTIES  \
0                   0.0                      0.0                        0.0   
1                   0.0                      0.0                        0.0   
2                   0.0                      0.0                        0.0   
3                   0.0                      0.0                        0.0   
4                   0.0                      0.0                        0.0   

   ACCESS_COARSE_LOCATION  ACCESS_COARSE_UPDATES  ACCESS_FINE_LOCATION  \
0                     0.0                    0.0                   0.0   
1                     0.0                    0.0                   0.0   
2                     0.0                    0.0                   0.0   
3                     0.0                    0.0                   0.0   
4                     0.0                    0.0                   0.0   

   ACCESS_LOCATION_EXTRA_COMMANDS  ACCESS_MOCK_LOCATION  ACCESS_MTK_MMHW  \
0                             0.0                   0.0              0.0   
1                             0.0                   0.0              0.0   
2                             0.0                   0.0              0.0   
3                             0.0                   0.0              0.0   
4                             0.0                   0.0              0.0   

   ACCESS_NETWORK_STATE  ...  \
0                   1.0  ...   
1                   1.0  ...   
2                   1.0  ...   
3                   0.0  ...   
4                   0.0  ...   

   Landroid/telephony/TelephonyManager;->getLine1Number  \
0                                                1.0      
1                                                0.0      
2                                                0.0      
3                                                0.0      
4                                                0.0      

   Landroid/telephony/TelephonyManager;->getNetworkOperator  \
0                                                1.0          
1                                                0.0          
2                                                0.0          
3                                                1.0          
4                                                0.0          

   Landroid/telephony/TelephonyManager;->getNetworkOperatorName  \
0                                                1.0              
1                                                0.0              
2                                                0.0              
3                                                1.0              
4                                                0.0              

   Landroid/telephony/TelephonyManager;->getNetworkCountryIso  \
0                                                0.0            
1                                                1.0            
2                                                0.0            
3                                                1.0            
4                                                0.0            

   Landroid/telephony/TelephonyManager;->getSimOperator  \
0                                                0.0      
1                                                0.0      
2                                                0.0      
3                                                1.0      
4                                                0.0      

   Landroid/telephony/TelephonyManager;->getSimOperatorName  \
0                                                0.0          
1                                                0.0          
2                                                0.0          
3                                                0.0          
4                                                0.0          

   Landroid/telephony/TelephonyManager;->getSimCountryIso  \
0                                                0.0        
1                                                

### Extracting the independant and dependant values matrix

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x = df.iloc[:,:-1].values
y = le.fit_transform(df['Label'])

In [14]:
y

array([1, 1, 1, ..., 0, 0, 0])

### Finding the missing value

In [15]:
missingvalue = df.isnull()

missingvalue.values.sum()

np.int64(1)

#### Encoding the categorical data of dependant variable y

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y=le.fit_transform(df['Label'])

In [17]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state = 1)


#### KNN Classification Model

In [19]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [20]:
y_pred = classifier.predict(x_test)

In [21]:
y_pred

array([1, 1, 0, ..., 0, 1, 1])

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(f"Confusion matrix = \n{cm}")
ac=accuracy_score(y_test,y_pred)
print(f"Accuracy = {ac}")
# Calculate precision, recall, and f1-score for both classes
if cm.shape[0] > 1:
    precision = cm[0][0] / (cm[0][0] + cm[0][1])
    recall = cm[0][0] / (cm[0][0] + cm[1][0])
    fscore = 2 * (precision * recall) / (precision + recall)
    print(f"Precision (Class 0) = {precision}")
    print(f"Recall (Class 0) = {recall}")
    print(f"F1Score (Class 0) = {fscore}")

    precision = cm[1][1] / (cm[1][1] + cm[1][0])
    recall = cm[1][1] / (cm[1][1] + cm[0][1])
    fscore = 2 * (precision * recall) / (precision + recall)
    print(f"Precision (Class 1) = {precision}")
    print(f"Recall (Class 1) = {recall}")
    print(f"F1Score (Class 1) = {fscore}")

Confusion matrix = 
[[ 253    7    0]
 [  11 1068    0]
 [   1    0    0]]
Accuracy = 0.985820895522388
Precision (Class 0) = 0.9730769230769231
Recall (Class 0) = 0.9583333333333334
F1Score (Class 0) = 0.9656488549618321
Precision (Class 1) = 0.989805375347544
Recall (Class 1) = 0.9934883720930232
F1Score (Class 1) = 0.9916434540389971


#### Decision Tree Classification Model

In [23]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [24]:
y_pred = classifier.predict(x_test)

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(f"Confusion matrix = \n{cm}")
ac=accuracy_score(y_test,y_pred)
print(f"Accuracy = {ac}")
# Calculate precision, recall, and f1-score for both classes
if cm.shape[0] > 1:
    precision = cm[0][0] / (cm[0][0] + cm[0][1])
    recall = cm[0][0] / (cm[0][0] + cm[1][0])
    fscore = 2 * (precision * recall) / (precision + recall)
    print(f"Precision (Class 0) = {precision}")
    print(f"Recall (Class 0) = {recall}")
    print(f"F1Score (Class 0) = {fscore}")

    precision = cm[1][1] / (cm[1][1] + cm[1][0])
    recall = cm[1][1] / (cm[1][1] + cm[0][1])
    fscore = 2 * (precision * recall) / (precision + recall)
    print(f"Precision (Class 1) = {precision}")
    print(f"Recall (Class 1) = {recall}")
    print(f"F1Score (Class 1) = {fscore}")

Confusion matrix = 
[[ 255    5    0]
 [  12 1067    0]
 [   1    0    0]]
Accuracy = 0.9865671641791045
Precision (Class 0) = 0.9807692307692307
Recall (Class 0) = 0.9550561797752809
F1Score (Class 0) = 0.967741935483871
Precision (Class 1) = 0.9888785912882299
Recall (Class 1) = 0.9953358208955224
F1Score (Class 1) = 0.99209669920967


#### Random Forest Classification Model

In [26]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100, criterion="entropy", random_state=0)
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [27]:
y_pred=classifier.predict(x_test)

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(f"Confusion matrix = \n{cm}")
ac=accuracy_score(y_test,y_pred)
print(f"Accuracy = {ac}")
# Calculate precision, recall, and f1-score for both classes
if cm.shape[0] > 1:
    precision = cm[0][0] / (cm[0][0] + cm[0][1])
    recall = cm[0][0] / (cm[0][0] + cm[1][0])
    fscore = 2 * (precision * recall) / (precision + recall)
    print(f"Precision (Class 0) = {precision}")
    print(f"Recall (Class 0) = {recall}")
    print(f"F1Score (Class 0) = {fscore}")

    precision = cm[1][1] / (cm[1][1] + cm[1][0])
    recall = cm[1][1] / (cm[1][1] + cm[0][1])
    fscore = 2 * (precision * recall) / (precision + recall)
    print(f"Precision (Class 1) = {precision}")
    print(f"Recall (Class 1) = {recall}")
    print(f"F1Score (Class 1) = {fscore}")

Confusion matrix = 
[[ 256    4    0]
 [   8 1071    0]
 [   1    0    0]]
Accuracy = 0.9902985074626866
Precision (Class 0) = 0.9846153846153847
Recall (Class 0) = 0.9696969696969697
F1Score (Class 0) = 0.9770992366412214
Precision (Class 1) = 0.9925857275254866
Recall (Class 1) = 0.9962790697674418
F1Score (Class 1) = 0.9944289693593314


# Execution time for the program

In [29]:
et = time.time()
exec_time = et - st
print (exec_time)

1.973353624343872
